"""v1.2 initial schema

Revision ID: aa44347edc4c
Revises: 
Create Date: 2026-07-18 11:42:45.016220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa44347edc4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PLACE',
    sa.Column('place_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ext_source', sa.String(length=10), nullable=False),
    sa.Column('ext_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('open_info', sa.JSON(), nullable=True),
    sa.Column('avg_stay_min', sa.SmallInteger(), nullable=False),
    sa.Column('price_level', sa.SmallInteger(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('ext_source', 'ext_id', name='uq_place_ext')
    )
    op.create_table('USER',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('login_fail_cnt', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('PROFILE',
    sa.Column('profile_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('travel_style', sa.String(length=20), nullable=False),
    sa.Column('food_pref', sa.JSON(), nullable=True),
    sa.Column('allergy', sa.Text(), nullable=True),  # EncryptedJSON — 저장 타입은 TEXT (암호화는 앱 계층)
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('walk_level', sa.SmallInteger(), nullable=False),
    sa.Column('budget_level', sa.SmallInteger(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('TRIP',
    sa.Column('trip_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('day_start', sa.Time(), nullable=False),
    sa.Column('day_end', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='ck_trip_dates'),
    sa.ForeignKeyConstraint(['owner_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('trip_id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('CHECKLIST',
    sa.Column('check_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.SmallInteger(), nullable=False),
    sa.Column('checked_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['USER.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['TRIP.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_table('EXPENSE',
    sa.Column('expense_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('spent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_expense_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['USER.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['TRIP.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('RECOMMENDATION',
    sa.Column('rec_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('rec_type', sa.String(length=15), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['PLACE.place_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['TRIP.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_table('SCHEDULE',
    sa.Column('schedule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('original_place_id', sa.BigInteger(), nullable=True),
    sa.Column('day_no', sa.SmallInteger(), nullable=False),
    sa.Column('order_no', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('stay_min', sa.SmallInteger(), nullable=False),
    sa.Column('move_min', sa.SmallInteger(), nullable=True),
    sa.Column('move_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_place_id'], ['PLACE.place_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['PLACE.place_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['TRIP.trip_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('trip_id', 'day_no', 'order_no', name='uq_sched_order')
    )
    op.create_table('TRIP_MEMBER',
    sa.Column('member_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['TRIP.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_member')
    )
    op.create_table('PLAN_B',
    sa.Column('planb_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('alt_place_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_type', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('rain_threshold', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alt_place_id'], ['PLACE.place_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planb_id'),
    sa.UniqueConstraint('schedule_id', 'priority', name='uq_planb_prio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PLAN_B')
    op.drop_table('TRIP_MEMBER')
    op.drop_table('SCHEDULE')
    op.drop_table('RECOMMENDATION')
    op.drop_table('EXPENSE')
    op.drop_table('CHECKLIST')
    op.drop_table('TRIP')
    op.drop_table('PROFILE')
    op.drop_table('USER')
    op.drop_table('PLACE')
    # ### end Alembic commands ###
